[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='0df6cb1b3f37ff519321cdca7b8c1678869fd78399397a8bfc293705d59d438a'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
